- name: Create additional mount directories
  file:
    path: "{{ item.target }}"
    state: directory
  loop: "{{ fstab_additional_mounts }}"
  when: fstab_create_additional_dirs
  listen: fstab_update

- name: Mount all fstab entries using `mount -a`
  shell: mount -a
  listen: fstab_update
  when: fstab_reload and fstab_reload_method == "mount"
